name: seethrough3d
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.1
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.17
  - parso=0.8.6
  - pexpect=4.9.0
  - pip=25.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.6.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - accelerate==1.10.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - bpy==4.3.0
      - brotli==1.1.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - contourpy==1.3.3
      - controlnet-aux==0.0.10
      - cycler==0.12.1
      - cython==3.1.3
      - datasets==4.4.1
      - diffusers==0.37.0.dev0
      - dill==0.4.0
      - einops==0.8.1
      - fastapi==0.118.0
      - ffmpy==0.6.1
      - filelock==3.18.0
      - flask==3.1.2
      - fonttools==4.59.1
      - frozenlist==1.8.0
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.0
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - image-gen-aux==0.1.0.dev0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.17.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - propcache==0.4.1
      - protobuf==6.32.0
      - pyarrow==22.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyparsing==3.2.3
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - rich==14.1.0
      - ruff==0.14.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.35.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - spandrel==0.4.1
      - starlette==0.48.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.9.9
      - timm==1.0.19
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.4.0
      - typer==0.19.2
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - voluptuous==0.16.0
      - wandb==0.25.0
      - websockets==15.0.1
      - werkzeug==3.1.5
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.23.0
prefix: /ssd_scratch/miniconda3/envs/bevlatents